# -*- coding: utf-8 -*-
"""머신러닝1-인트로.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nI0-H85yqV4l5vuId450JF6SWikr3ApY

# 인공지능의 정의
* 인간의 지능을 기계로 구현하는 모든 형태

# 인공지능의 범위
인공지능 > 머신러닝 > 딥러닝

![](https://github.com/hanrury/-/blob/master/deep-learning-evolution.png?raw=true)

# 인공지능 구현방식
* 초기에는 지식전달 방식으로 구현
  + 개발자가 기계에게 일반적인 규칙을 알려줌
  + 심한 변환의 양상에는 잘 대처하지 못함

* 후기에는 데이터중심으로 구현
  + 데이터를 중심으로 기계가 학습(규칙/패턴인식) 한뒤
  + 새로운 데이터를 통해 예측/분류함
  + 학습을 위한 많은 양질의 데이터가 필요

# 머신러닝
* 컴퓨터가 경험을 통해 학습할수 있도록 프로그래밍하되 세세하게 프로그래밍 해야하는 번거로움에서 벗어나게 하는 것

# 머신러닝 알고리즘
* 지도학습 : 데이터와 레이블(정답)을 통해 훈련 수행
  + 분류 : 범주형데이터, 이진분류, 다항분류
  - ex) 개, 고양이 사진 분류, 스팸분류
  - KNN, 의사결정나무, 로지스틱회귀, 나이브베이즈, SVM, 신경망, 부스팅

  + 회귀 :연속형데이터, 예측
  - ex) 주식시세 예측
  - 선형회귀, 의사결정나무, 부스팅, 신경망 

* 비지도학습 : 데이터만을 통해 학습
  + 군집화 : 유사한 성격의 데이터들끼리 모음
  - ex) 추천시스템,고객별 티켓 마케팅
  - kmeans

  + 차원축소 : 독립변수의 개수를 줄임
  - ex) 변수제거, 시각화
  - PCA

![](https://github.com/hanrury/-/blob/master/KakaoTalk_20200728_111213223.png?raw=true)

# 머신러닝 처리 과정
* 지도학습
  + 훈련데이터와 레이블 준비
  + 훈련데이터에서 특성 추출후 레이블과 학습 진행
  + 평가데이터를 이용해서 학습의 결과로 만들어진 모델을 평가
  + 새로운 데이터로 모델을 통해 예측

* 비지도학습
  + 훈련데이터 준비
  + 훈련데이터에서 특성 추출후 학습 진행
  + 평가데이터를 이용해서 학습의 결과로 만들어진 모델을 평가
  + 새로운 데이터로 모델을 통해 예측
  
![](https://github.com/hanrury/machine-learning/blob/master/ML%20processing.png?raw=true)

# 알아두면 좋은 참고 사이트
* tensorflow.blog
"""

